# Generated by Django 5.1.2 on 2024-11-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmIdeas', '0003_idea_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='slug',
            field=models.SlugField(),
        ),
    ]
